name: CI

on:
  # @todo: add running build on new commits on PR as well.
  pull_request

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv
      - name: Check coding standards for modules and theme
        uses: docker://hussainweb/drupalqa:php7.4
        with:
          args: phpcs --standard="Drupal,DrupalPractice" -n --extensions="php,module,install,theme" web/themes/imalabya web/modules/custom --ignore=web/themes/*/dist/,web/themes/*/Gulpfile.js,web/themes/*/node_modules/
      - name: Run a one-line script CUSTOOOMM !
        run: echo Hello, world!; ls -alh;
      - name: Setup Docksal
        # You may pin to the exact commit or the version.
        # uses: twfahey1/setup-docksal@03dc8602295aa815e1c40ca7bd82ede48d740938
        uses: twfahey1/setup-docksal@0.4
      - name: Run custom command
        run: fin drush status
