name: CI

on:
  # @todo: add running build on new commits on PR as well.
  pull_request:
    types:
      - opened

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run custom command
        run: fin drush status
